CREATE DATABASE IF NOT EXISTS BD_GRUPOS_TCC;
USE BD_GRUPOS_TCC;

CREATE TABLE IF NOT EXISTS GRUPO(
	GRUPO_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    GRUPO_TEMA VARCHAR(255) NOT NULL,
    GRUPO_PO VARCHAR(255) NOT NULL,
    GRUPO_TURMA VARCHAR(1) NOT NULL,
    GRUPO_DATA_CADASTRO DATETIME NOT NULL
);

CREATE TABLE IF NOT EXISTS ALUNO(
	ALUNO_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    ALUNO_NOME VARCHAR(255) NOT NULL,
    ALUNO_PAPEL VARCHAR(100) NOT NULL,
    ALUNO_FK_GRUPO_ID INTEGER NOT NULL,
    FOREIGN KEY (ALUNO_FK_GRUPO_ID) REFERENCES GRUPO(GRUPO_ID)
);